baseURL = "https://skobrain.org/"
languageCode = "en-us"
title = "Skoblenick Lab"
theme = "PaperMod"

# Enable the home layout (for _index.md)
[params]
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"   # or "light" / "dark"
  disableScrollToTop = false
  mainSections = ["posts"]

# Optional: top menu bar
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
	identifier = "contact"
	name = "Contact"
	url = "/contact/"
	weight = 3