baseURL = "https://skobrain.org/"
languageCode = "en-us"
title = "Skobrain Lab"
theme = "PaperMod"

# Enable the home layout (for _index.md)
[params]
  homeInfoParams = true
  description = "Emergency Medicine | Neuroscience | Behavioural Health"
  ShowShareButtons = false
  ShowReadingTime = true

# Optional: top menu bar
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/posts/about"
    weight = 1

  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/posts/publications"
    weight = 2

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv.pdf"
    weight = 3